apiVersion: v1
kind: Namespace
metadata:
  name: ${SC2_NAMESPACE}
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-world
  namespace: ${SC2_NAMESPACE}
spec:
  template:
    metadata:
      annotations:
        io.containerd.cri.runtime-handler: ${RUNTIME_CLASS_NAME}
      labels:
        apps.sc2.io/name: hello-world
    spec:
      runtimeClassName: ${RUNTIME_CLASS_NAME}
      securityContext:
        runAsUser: 1000
      containers:
        - image: ${CTR_REGISTRY_URL}/hello-world:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
